# Generated by Django 5.2.8 on 2026-01-08 22:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0004_occupationrequest_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='GNF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('HELD_IN_ESCROW', 'Retenu en séquestre'), ('RELEASED', 'Fonds libérés'), ('REFUNDED', 'Remboursé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money'), ('WAVE', 'Wave'), ('BANK_TRANSFER', 'Virement bancaire'), ('CASH', 'Espèces')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID de transaction du fournisseur', max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, help_text='Réponse complète du fournisseur', null=True)),
                ('payment_phone', models.CharField(blank=True, help_text='Numéro utilisé pour le paiement', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('occupation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.occupationrequest')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('HOLDING', 'Fonds retenus'), ('RELEASED', 'Fonds libérés'), ('REFUNDED', 'Remboursé')], default='HOLDING', max_length=20)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('release_scheduled_date', models.DateTimeField(blank=True, help_text='Date prévue de libération automatique', null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.payment')),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Raison du litige')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('INVESTIGATING', "En cours d'investigation"), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('REFUND_FULL', 'Remboursement total'), ('REFUND_PARTIAL', 'Remboursement partiel'), ('NO_REFUND', 'Pas de remboursement')], max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.payment')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('distribution_type', models.CharField(choices=[('OWNER_PAYMENT', 'Paiement propriétaire'), ('AGENT_COMMISSION', 'Commission agent'), ('PLATFORM_FEE', 'Frais de plateforme')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('transfer_reference', models.CharField(blank=True, max_length=255)),
                ('transfer_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='payments.payment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_distributions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money'), ('WAVE', 'Wave')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, help_text='Ex: Mon Orange Money principal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Paiement'), ('REFUND', 'Remboursement'), ('COMMISSION', 'Commission'), ('TRANSFER', 'Transfert'), ('FEE', 'Frais')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', '-created_at'], name='payments_pa_payer_i_5351f5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'method_type', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment', '-created_at'], name='payments_tr_payment_d6d3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='payments_tr_transac_635543_idx'),
        ),
    ]
