# Generated by Django 5.2.8 on 2026-01-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('CHAMBRE_SIMPLE', 'Rentrée Couchée'), ('SALON_CHAMBRE', 'Salon Chambre'), ('APPARTEMENT', 'Appartement')], max_length=20),
        ),
        migrations.CreateModel(
            name='ManagementMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('CHAMBRE_SIMPLE', 'Rentrée Couchée'), ('SALON_CHAMBRE', 'Salon Chambre'), ('APPARTEMENT', 'Appartement')], max_length=20)),
                ('location_description', models.TextField(help_text="Description précise de l'emplacement du bien")),
                ('property_description', models.TextField(help_text='Détails sur le bien (nombre de pièces, état, etc.)')),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('owner_phone', models.CharField(help_text='Numéro à contacter (WhatsApp ou direct)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
