# Generated by Django 5.2.8 on 2026-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementmandate',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage de commission (ex: 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='managementmandate',
            name='mandate_type',
            field=models.CharField(choices=[('EXCLUSIVE', 'Exclusif'), ('SIMPLE', 'Simple (Non-exclusif)')], default='SIMPLE', max_length=20),
        ),
        migrations.AddField(
            model_name='managementmandate',
            name='signature_agent',
            field=models.CharField(blank=True, help_text='Signature numérique du démarcheur', max_length=255),
        ),
        migrations.AddField(
            model_name='managementmandate',
            name='signature_owner',
            field=models.CharField(blank=True, help_text='Signature numérique du propriétaire', max_length=255),
        ),
        migrations.AddField(
            model_name='managementmandate',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
