# Generated by Django 5.2.8 on 2026-01-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_managementmandate_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementmandate',
            name='property_type',
            field=models.CharField(choices=[('CHAMBRE_SIMPLE', 'Rentrée Couchée'), ('SALON_CHAMBRE', 'Salon Chambre'), ('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('STUDIO', 'Studio'), ('MAGASIN', 'Magasin'), ('BUREAU', 'Bureau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('CHAMBRE_SIMPLE', 'Rentrée Couchée'), ('SALON_CHAMBRE', 'Salon Chambre'), ('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('STUDIO', 'Studio'), ('MAGASIN', 'Magasin'), ('BUREAU', 'Bureau')], max_length=20),
        ),
    ]
