# Generated by Django 5.2.8 on 2026-01-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_managementmandate_property_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='properties.managementmandate')),
            ],
            options={
                'verbose_name_plural': 'Mandate histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
