# Generated by Django 5.2.8 on 2026-01-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_mandatehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='description_direction',
            field=models.TextField(blank=True, help_text='Instructions de direction (ex: 2ème ruelle après le manguier)'),
        ),
        migrations.AddField(
            model_name='property',
            name='plus_code',
            field=models.CharField(blank=True, help_text="Code d'adresse numérique (ex: 89P5+XJ)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='point_de_repere',
            field=models.TextField(blank=True, help_text='Repère visuel (ex: À 50m de la Mosquée)'),
        ),
    ]
