# Generated by Django 5.2.8 on 2026-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
    ]
