# Generated by Django 5.2.8 on 2026-01-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.FloatField(default=5.0, help_text='Note de réputation sur 5'),
        ),
    ]
