# Generated by Django 5.2.8 on 2026-01-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
