# Generated by Django 5.2.8 on 2026-01-08 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_agent'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('validation_code', models.CharField(help_text='Code à 6 chiffres à valider lors de la visite', max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé (Visite effectuée)'), ('MISSED', 'Non honoré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Note sur 5', null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_as_agent', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_as_visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
