# Generated by Django 5.2.8 on 2026-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_visitvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitvoucher',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation de la visite', null=True),
        ),
    ]
