# Generated by Django 5.2.8 on 2026-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_visitvoucher_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationrequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant à payer (calculé automatiquement)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='occupationrequest',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Date limite pour effectuer le paiement', null=True),
        ),
        migrations.AddField(
            model_name='occupationrequest',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Non payé'), ('PAID', 'Payé'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='occupationrequest',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='Si ce logement nécessite un paiement'),
        ),
    ]
