# Generated by Django 5.2.8 on 2026-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_occupationrequest_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitvoucher',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Demande envoyée'), ('ACCEPTED', 'Acceptée (En attente)'), ('VALIDATED', 'Validée (Visite effectuée)'), ('REJECTED', 'Refusée'), ('MISSED', 'Non honorée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20),
        ),
    ]
