# Generated by Django 5.2.8 on 2026-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_visitvoucher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitvoucher',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitvoucher',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Demande envoyée'), ('ACCEPTED', 'Acceptée (En attente)'), ('VALIDATED', 'Validée (Visite effectuée)'), ('REJECTED', 'Refusée'), ('MISSED', 'Non honorée'), ('CANCELLED', 'Annulée')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitvoucher',
            name='validation_code',
            field=models.CharField(blank=True, help_text='Code à 6 chiffres à valider lors de la visite', max_length=6),
        ),
    ]
